defaults:
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled  
    - _self_

# task
tasks: [PickCube-v1-multicam-groundless, PushCube-v1-multicam-groundless, StackCube-v1-multicam-groundless]
steps: 2000000
seed: 0
exp_name: test_dreamerv3
eval_freq: 180
save_freq: 900
eval_episodes: 20

# wandb
wandb_project: nerf-pose-prior
wandb_entity: project-ava
wandb_enable: true

# dirs
logging_dir: ./logs

hydra:  
  output_subdir: null  
  run:  
    dir: .