defaults:
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled  
    - _self_

# task
task: PushCube-v1-multicam-groundless
steps: 2000000
seed: 0
exp_name: test_dreamerv3
eval_freq: 50000
eval_episodes: 10

# wandb
wandb_project: nerf-pose-prior
wandb_entity: project-ava
wandb_enable: false

# dirs
logging_dir: ./logs

hydra:  
  output_subdir: null  
  run:  
    dir: .